namespace eStore.Services.Interfaces {

    public interface ILanguageService
    {
        /// <summary>
        /// Gets the response asynchronously based on the user input.
        /// </summary>
        /// <param name="userInput">The user input to process.</param>
        /// <returns>The response generated by processing the user input.</returns>
        Task<string> GetResponseAsync(string userInput);
    }

}
